export const APP_ENV_DEVELOPPEMENT = "APP_ENV_DEVELOPPEMENT";
export const APP_ENV_RECIPE = "APP_ENV_RECIPE";
export const APP_ENV_INTEGRATION = "APP_ENV_INTEGRATION";
export const APP_ENV_PRODUCTION = "APP_ENV_PRODUCTION";
